version: '3.8'
services:
  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
  api:
    container_name: api
    image: rgb-matrix-api:latest
    restart: always
    environment:
      - REDIS_HOST=redis
    ports:
     - '8000:8000'
    depends_on:
      - redis
  client:
    container_name: client
    image: rgb-matrix-client:latest
    restart: always
    environment:
      - REDIS_HOST=redis
    privileged: true
    depends_on:
      - redis
volumes:
  cache:
    driver: local
networks:
  services:
    driver: bridge
